#include "funcionesProducto/crearProducto.h"
#include "funcionesProducto/buscarProducto.h"
#include "funcionesProducto/consultarProductos.h"
#include "funcionesProducto/imprimirProducto.h"
#include "funcionesProducto/cambiarPrecioProducto.h"
#include "funcionesProducto/cambiarStockProducto.h"
